# Generated by Django 4.1.2 on 2022-10-23 16:39

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[users.validators.AgeMinValidator(9)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.EmailValidator(), users.validators.EmailNotAllowValidator('rambler.ru')]),
        ),
    ]
